language: php
php:
  - '7.0'
services:
    - redis-server
install:
  - ./composer.phar install --no-interaction
before_script:
  - redis-cli info
script:
  - ./vendor/bin/phpcs --standard=Symfony3Custom --extensions=php src/ tests/
  - ./phpunit.phar --debug
