
# AppBundle > DefaultController

default_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index


# AppBundle > GameController

game_index:
    path:     /game/start
    defaults:
        _controller: AppBundle:Game:start

game_index_id:
    path:     /game/{id}
    defaults:
        _controller: AppBundle:Game:indexId

game_move_card:
    path:     /game/{id}/move/card/{card}/from/{fromUserId}/to/{toUserId}
    defaults:
        _controller: AppBundle:Game:moveCard
