
# AppBundle > DefaultController

default_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index


# AppBundle > GameController

game_index:
    path:     /game/start
    defaults:
        _controller: AppBundle:Game:start
