
# AppBundle > DefaultController

default_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index


# AppBundle > GameController

game_start:
    path:     /game/start
    methods:  [GET]
    defaults:
        _controller: AppBundle:Game:start

game_index:
    path:     /game
    methods:  [GET]
    defaults:
        _controller: AppBundle:Game:index

# TODO: Remove GET from following routes later
game_join:
    path:     /game/{gameId}/join/{atSN}
    methods:  [POST, GET]
    defaults:
        _controller: AppBundle:Game:join

game_move_card:
    path:     /game/move/{card}/from/{fromUserId}
    methods:  [PATCH, GET]
    defaults:
        _controller: AppBundle:Game:moveFrom

game_delete:
    path:     /game/delete
    methods:  [DELETE, GET]
    defaults:
        _controller: AppBundle:Game:delete
