
# AppBundle > DefaultController

default_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index


# AppBundle > GameController

game_start:
    path:     /game/start
    defaults:
        _controller: AppBundle:Game:start

game_index_id:
    path:     /game/{id}
    defaults:
        _controller: AppBundle:Game:indexId

game_join_gameid:
    path:     /join/{gameId}/{userSN}
    defaults:
        _controller: AppBundle:Game:joinId

game_move_card:
    path:     /game/{id}/move/card/{card}/from/{fromUserSN}/to/{toUserSN}
    defaults:
        _controller: AppBundle:Game:moveCard
