
# AppBundle > DefaultController

default_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index


# AppBundle > GameController

game_start:
    path:     /game/start
    defaults:
        _controller: AppBundle:Game:start

game_index:
    path:     /game/{id}
    defaults:
        _controller: AppBundle:Game:index

game_join:
    path:     /game/{gameId}/join/{userSN}
    defaults:
        _controller: AppBundle:Game:join

game_move_card:
    path:     /game/{id}/move/card/{card}/from/{fromUserSN}/to/{toUserSN}
    defaults:
        _controller: AppBundle:Game:moveCard

game_delete:
    path:     /game/{id}/delete
    defaults:
        _controller: AppBundle:Game:delete
