
# AppBundle > DefaultController

default_index:
    path:            /
    methods:         [GET]
    defaults:
        _controller: AppBundle:Default:index

# AppBundle > D

default_demo:
    path:            /demo
    methods:         [GET]
    defaults:
        _controller: AppBundle:Default:demo


# AppBundle > GameController

game_index:
    path:            /game
    methods:         [GET]
    defaults:
        _controller: AppBundle:Game:index

# TODO:
#     - Remove GET from following routes after dev complete.

game_start:
    path:            /game/start
    methods:         [POST, GET]
    defaults:
        _controller: AppBundle:Game:start

game_join:
    path:            /game/{gameId}/join/{team}
    methods:         [POST, GET]
    defaults:
        _controller: AppBundle:Game:join

game_move_card:
    path:            /game/move/{card}/from/{fromUserId}
    methods:         [POST, GET]
    defaults:
        _controller: AppBundle:Game:moveFrom

game_show:
    path:            /game/show/{cardType}/{cardRange}
    methods:         [POST, GET]
    defaults:
        _controller: AppBundle:Game:show

game_delete:
    path:            /game/delete
    methods:         [DELETE, GET]
    defaults:
        _controller: AppBundle:Game:delete


# AppBundle > ChatController

chat_post:
    path:            /chat
    methods:         [POST, GET]
    defaults:
        _controller: AppBundle:Chat:post
