# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app_bundle.pubsub.pusher:
        class:        AppBundle\Service\PubSub\Pusher
        arguments:
            - "%pusher.mock%"
            - "@logger"
            - "%pusher.app_key%"
            - "%pusher.app_secret%"
            - "%pusher.app_id%"
        factory:      ['AppBundle\Service\PubSub\Pusher', create]

    app_bundle.knowledge:
        class:        AppBundle\Service\KnowledgeService
        arguments:
            - "@logger"
            - "@snc_redis.default"

    app_bundle.game:
        class:        AppBundle\Service\GameService
        arguments:
            - "@logger"
            - "@snc_redis.default"
            - "@app_bundle.pubsub.pusher"
            - "@app_bundle.knowledge"


    # Event subscriber services
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionSubscriber
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }

    app.request_subscriber:
        class: AppBundle\EventSubscriber\RequestSubscriber
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }
